-- Cleanup
-- Driver table
SELECT * FROM driver;
SHOW FIELDS FROM driver FROM 2018_f1_season; 

ALTER TABLE driver
MODIFY COLUMN Total INT,
MODIFY COLUMN `1` INT, MODIFY COLUMN `2` INT, MODIFY COLUMN `3` INT,
MODIFY COLUMN `4` INT, MODIFY COLUMN `5` INT, MODIFY COLUMN `6` INT,
MODIFY COLUMN `7` INT, MODIFY COLUMN `8` INT, MODIFY COLUMN `9` INT,
MODIFY COLUMN `10` INT, MODIFY COLUMN `11` INT, MODIFY COLUMN `12` INT,
MODIFY COLUMN `13` INT, MODIFY COLUMN `14` INT, MODIFY COLUMN `15` INT,
MODIFY COLUMN `16` INT, MODIFY COLUMN `17` INT, MODIFY COLUMN `18` INT,
MODIFY COLUMN `19` INT, MODIFY COLUMN `20` INT, MODIFY COLUMN `21` INT;

-- Driver_team
SELECT * FROM driver_team;
SHOW FIELDS FROM driver_team FROM 2018_f1_season; 

-- Fastest_pitstops
SELECT * FROM fastest_pitstops;
SHOW FIELDS FROM fastest_pitstops FROM 2018_f1_season; 

UPDATE  fastest_pitstops -- fill empty value
  SET FRE = NULL
WHERE FRE = '';

ALTER TABLE fastest_pitstops        -- change column data types
MODIFY COLUMN AUST FLOAT(4, 2), MODIFY COLUMN BAH FLOAT(4, 2), MODIFY COLUMN CHI FLOAT(4, 2),
MODIFY COLUMN AZE FLOAT(4, 2), MODIFY COLUMN SPA FLOAT(4, 2), MODIFY COLUMN MON FLOAT(4, 2),
MODIFY COLUMN CAN FLOAT(4, 2), MODIFY COLUMN FRE FLOAT(4, 2), MODIFY COLUMN AUS FLOAT(4, 2),
MODIFY COLUMN BRI FLOAT(4, 2), MODIFY COLUMN GER FLOAT(4, 2), MODIFY COLUMN HUN FLOAT(4, 2),
MODIFY COLUMN BEL FLOAT(4, 2), MODIFY COLUMN ITA FLOAT(4, 2), MODIFY COLUMN SIN FLOAT(4, 2),
MODIFY COLUMN RUS FLOAT(4, 2), MODIFY COLUMN JAP FLOAT(4, 2), MODIFY COLUMN UNI FLOAT(4, 2),
MODIFY COLUMN MEX FLOAT(4, 2), MODIFY COLUMN BRA FLOAT(4, 2), MODIFY COLUMN ABU FLOAT(4, 2);
-- fill null with minimum value
SET @min_value = (SELECT MIN(FRE) -- set variable with the minimum value 
			      FROM fastest_pitstops
                  WHERE FRE IS NOT NULL);
UPDATE fastest_pitstops
   SET FRE = @min_value
WHERE FRE IS NULL;

-- laps_led
SELECT * FROM laps_led;
SHOW FIELDS FROM laps_led FROM 2018_f1_season; 
-- extract percentages from the data
UPDATE laps_led
SET `Full season laps led` = CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`Full season laps led`, 
								  '(', -1), '%', 1) AS DECIMAL(4, 2)),
    `Driver's season laps led` = CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`Driver's season laps led`, 
								  '(', -1), '%', 1) AS DECIMAL(4, 2));
 -- DTTYPE
ALTER TABLE laps_led
MODIFY COLUMN `Full season laps led` FLOAT(4, 2),
MODIFY COLUMN `Driver's season laps led` FLOAT(4, 2);

-- laps per position
SELECT * FROM laps_per_position;
SHOW FIELDS FROM laps_per_position FROM 2018_f1_season;

ALTER TABLE laps_per_position
MODIFY COLUMN `1` INT, MODIFY COLUMN `2` INT, MODIFY COLUMN `3` INT,
MODIFY COLUMN `4` INT, MODIFY COLUMN `5` INT, MODIFY COLUMN `6` INT,
MODIFY COLUMN `7` INT, MODIFY COLUMN `8` INT, MODIFY COLUMN `9` INT,
MODIFY COLUMN `10` INT, MODIFY COLUMN `11` INT, MODIFY COLUMN `12` INT,
MODIFY COLUMN `13` INT, MODIFY COLUMN `14` INT, MODIFY COLUMN `15` INT,
MODIFY COLUMN `16` INT, MODIFY COLUMN `17` INT, MODIFY COLUMN `18` INT,
MODIFY COLUMN `19` INT, MODIFY COLUMN `20` INT;

-- Penalties
SELECT * FROM penalties;
SHOW FIELDS FROM penalties FROM 2018_f1_season;

ALTER TABLE penalties
MODIFY COLUMN `Penalties due to driver` INT,
MODIFY COLUMN `Penalties due to team` INT,
MODIFY COLUMN `No action` INT;

-- pit_stops
SELECT * FROM pit_stop;
SHOW FIELDS FROM pit_stop FROM 2018_f1_season;

ALTER TABLE pit_stop
MODIFY COLUMN `1` INT, MODIFY COLUMN `2` INT, MODIFY COLUMN `3` INT,
MODIFY COLUMN `4` INT, MODIFY COLUMN `5` INT, MODIFY COLUMN `6` INT,
MODIFY COLUMN `7` INT, MODIFY COLUMN `8` INT, MODIFY COLUMN `9` INT,
MODIFY COLUMN `10` INT, MODIFY COLUMN `11` INT, MODIFY COLUMN `12` INT,
MODIFY COLUMN `13` INT, MODIFY COLUMN `14` INT, MODIFY COLUMN `15` INT,
MODIFY COLUMN `16` INT, MODIFY COLUMN `17` INT, MODIFY COLUMN `18` INT,
MODIFY COLUMN `19` INT, MODIFY COLUMN `20` INT, MODIFY COLUMN `21` INT;

-- pos_change_lap_one
SELECT * FROM pos_change_lap_one;
SHOW FIELDS FROM pos_change_lap_one FROM 2018_f1_season;

ALTER TABLE pos_change_lap_one
MODIFY COLUMN Average FLOAT(4, 2),
MODIFY COLUMN Total FLOAT(4, 2);

-- q1q2q3
DROP TABLE q1q2q3;

-- qualifying
SELECT * FROM qualifying;
SHOW FIELDS FROM qualifying FROM 2018_f1_season;

ALTER TABLE qualifying
MODIFY COLUMN Average FLOAT(4, 2),
MODIFY COLUMN AUST INT, MODIFY COLUMN BAH INT, MODIFY COLUMN CHI INT,
MODIFY COLUMN AZE INT, MODIFY COLUMN SPA INT, MODIFY COLUMN MON INT,
MODIFY COLUMN CAN INT, MODIFY COLUMN FRE INT, MODIFY COLUMN AUS INT,
MODIFY COLUMN BRI INT, MODIFY COLUMN GER INT, MODIFY COLUMN HUN INT,
MODIFY COLUMN BEL INT, MODIFY COLUMN ITA INT, MODIFY COLUMN SIN INT,
MODIFY COLUMN RUS INT, MODIFY COLUMN JAP INT, MODIFY COLUMN UNI INT,
MODIFY COLUMN MEX INT, MODIFY COLUMN BRA INT, MODIFY COLUMN ABU INT;

-- qualifying_sessions
SELECT * FROM qualifying_sessions;
SHOW FIELDS FROM qualifying_sessions FROM 2018_f1_season;

ALTER TABLE qualifying_sessions
MODIFY COLUMN `Eliminated in Q1` INT,
MODIFY COLUMN `Eliminated in Q2` INT,
MODIFY COLUMN `Reached Q3` INT;

-- retirements
SELECT * FROM retirements;
SHOW FIELDS FROM retirements FROM 2018_f1_season;

ALTER TABLE retirements
MODIFY COLUMN Accident INT,
MODIFY COLUMN `Technical failure` INT,
MODIFY COLUMN NC INT,
MODIFY COLUMN DQ INT,
MODIFY COLUMN DNQ INT,
MODIFY COLUMN DNS INT,
MODIFY COLUMN W INT;

-- start_and_fin
SELECT * FROM start_and_fin;
SHOW FIELDS FROM start_and_fin FROM 2018_f1_season;

ALTER TABLE start_and_fin
MODIFY COLUMN Started INT,
MODIFY COLUMN Classified INT,
MODIFY COLUMN Completed INT;

-- start_position
SELECT * FROM start_position;
SHOW FIELDS FROM start_position  FROM 2018_f1_season;

ALTER TABLE start_position
MODIFY COLUMN Average FLOAT(4, 2),
MODIFY COLUMN AUST INT, MODIFY COLUMN BAH INT, MODIFY COLUMN CHI INT,
MODIFY COLUMN AZE INT, MODIFY COLUMN SPA INT, MODIFY COLUMN MON INT,
MODIFY COLUMN CAN INT, MODIFY COLUMN FRE INT, MODIFY COLUMN AUS INT,
MODIFY COLUMN BRI INT, MODIFY COLUMN GER INT, MODIFY COLUMN HUN INT,
MODIFY COLUMN BEL INT, MODIFY COLUMN ITA INT, MODIFY COLUMN SIN INT,
MODIFY COLUMN RUS INT, MODIFY COLUMN JAP INT, MODIFY COLUMN UNI INT,
MODIFY COLUMN MEX INT, MODIFY COLUMN BRA INT, MODIFY COLUMN ABU INT;

-- team
SELECT * FROM team;
SHOW FIELDS FROM team FROM 2018_f1_season;

ALTER TABLE team
MODIFY COLUMN Total INT,
MODIFY COLUMN `1` INT, MODIFY COLUMN `2` INT, MODIFY COLUMN `3` INT,
MODIFY COLUMN `4` INT, MODIFY COLUMN `5` INT, MODIFY COLUMN `6` INT,
MODIFY COLUMN `7` INT, MODIFY COLUMN `8` INT, MODIFY COLUMN `9` INT,
MODIFY COLUMN `10` INT, MODIFY COLUMN `11` INT, MODIFY COLUMN `12` INT,
MODIFY COLUMN `13` INT, MODIFY COLUMN `14` INT, MODIFY COLUMN `15` INT,
MODIFY COLUMN `16` INT, MODIFY COLUMN `17` INT, MODIFY COLUMN `18` INT,
MODIFY COLUMN `19` INT, MODIFY COLUMN `20` INT, MODIFY COLUMN `21` INT;

-- Teammate_comparison
SELECT * FROM teammate_comparison;
SHOW FIELDS FROM teammate_comparison FROM 2018_f1_season;
-- remove trailing s's
UPDATE teammate_comparison
SET `Average gap to team mate` = RTRIM(`Average gap to team mate`);

SELECT SUBSTR(`Average gap to team mate`,  (LENGTH(`Average gap to team mate`) -1))
FROM teammate_comparison;
